name: Lint
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  golangci:
    name: Go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
